version: 2

jobs:
  build:
    docker:
      - image: circleci/node:10
    working_directory: ~/repo
    steps:
      - checkout
      - run:
          name: Install Dependencies
          command: npm install -g mintable
      - run:
          name: Mintable
          command: mintable fetch

workflows:
  version: 2
  daily:
    triggers:
      - schedule:
          # 10AM UTC = 6AM EST daily
          cron: "0 10 * * *"
          filters:
            branches:
              only:
                - master
    jobs:
      - build
