version: 2

jobs:
  build:
    docker:
      - image: circleci/node:10
    working_directory: ~/repo
    steps:
      - checkout
      - restore_cache:
          name: Restore Yarn Package Cache
          keys:
            - yarn-packages-{{ checksum "yarn.lock" }}
      - run:
          name: Install Dependencies
          command: yarn install --frozen-lockfile
      - save_cache:
          name: Save Yarn Package Cache
          key: yarn-packages-{{ checksum "yarn.lock" }}
          paths:
            - ~/.cache/yarn
      - run: yarn mintable

workflows:
  version: 2
  hourly:
    triggers:
      - schedule:
          # Hourly cron tab at 12:00, 1:00, etc.
          cron: "0 * * * *"
          filters:
            branches:
              only:
                - master
    jobs:
      - build
