name: Fetch

on:
  push:
    branches: [ master, release/2.0.0 ]
  pull_request:
    branches: [ master, release/2.0.0 ]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [10.x, 12.x, 14.x]

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
      env:
        MINTABLE_CONFIG: ${{ secrets.MINTABLE_CONFIG }}
    - run: npm install
    - run: npm run build
    - run: npm run mintable fetch
